# Generated by Django 5.2.8 on 2025-12-01 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        # Rename 'name' field to 'skill'
        migrations.RenameField(
            model_name='skill',
            old_name='name',
            new_name='skill',
        ),
        # Remove the 'user' field
        migrations.RemoveField(
            model_name='skill',
            name='user',
        ),
    ]
