# Generated by Django 5.2.8 on 2025-12-04 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_rename_name_skill_skill_remove_skill_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
    ]
